#!/bin/bash
#
# Temporary script to start tgt
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
MEM_SIZE=1048576

#
# Need to select one
#
#TARGET=ibmvio
TARGET=iscsi_tcp

#
# IBM pSeries VIO server
#
start_ibmvio()
{
	insmod ${PWD}/ibmvstgt/kernel/libsrp.ko
	insmod ${PWD}/ibmvstgt/kernel/ibmvstgt.ko
}

stop_ibmvio()
{
	rmmod libsrp
	rmmod ibmvstgt
}


#
# iSCSI stuff
#
start_iscsi_core()
{
	insmod ${PWD}/istgt/kernel/scsi_transport_iscsi.ko
	insmod ${PWD}/istgt/kernel/libiscsi.ko
}

stop_iscsi_core()
{
	rmmod libiscsi
	rmmod scsi_transport_iscsi
}

start_iscsi_tcp()
{
	modprobe -q crc32c

	start_iscsi_core

	insmod ${PWD}/istgt/kernel/iscsi_tcp.ko
	insmod ${PWD}/istgt/kernel/iscsi_tcp_target.ko
}

stop_iscsi_tcp()
{
	rmmod iscsi_tcp_target
	rmmod iscsi_tcp
}

start_iscsi_iser()
{
    	start_iscsi_core
}

start_server()
{
	insmod ${PWD}/kernel/scsi_tgt.ko

	case "$TARGET" in
	    iscsi_tcp)
		start_iscsi_tcp
		;;
	    ibmvio)
		start_ibmvio
		;;
	    *)
		;;
	esac

	${PWD}/usr/tgtd -d8 --drivers iscsi

	sleep 1
}
	
stop_server()
{
	case "$TARGET" in
	    iscsi_tcp)
		${PWD}/usr/tgtadm --driver istgt --op delete
		killall -9 istgtd
		;;
	    ibmvio)
		${PWD}/usr/tgtadm --driver ibmvstgt --op delete
		;;
	    *)
		;;
	esac

	killall -9 tgtd

	sleep 1

	case "$TARGET" in
	    iscsi_tcp)
		stop_iscsi_tcp
		;;
	    ibmvio)
		stop_ibmvio
		;;
	    *)
		;;
	esac

	rmmod scsi_tgt
}

case "$1" in
	start)
		start_server
		;;
	stop)
		stop_server
		;;
	*)
		echo "Usage: {start|stop}" >&2
		exit 1
		;;
esac

exit 0
