#!/bin/bash
#
# Temporary script to start tgt and istgt
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
MEM_SIZE=1048576

start_server()
{
	insmod ${PWD}/kernel/tgt_core.ko
	insmod ${PWD}/kernel/tgt_scsi.ko
	insmod ${PWD}/kernel/tgt_vsd.ko
#	insmod ${PWD}/kernel/tgt_sd.ko

	modprobe -q crc32c
	insmod ${PWD}/istgt/kernel/iscsi_trgt.ko

	${PWD}/usr/tgtd
}
	
stop_server()
{
	${PWD}/usr/tgtadm --op delete
	killall -9 tgtd

	rmmod iscsi_trgt

#	rmmod tgt_sd
	rmmod tgt_vsd
	rmmod tgt_scsi
	rmmod tgt_core
}

case "$1" in
	start)
		start_server
		;;
	stop)
		stop_server
		;;
	*)
		echo "Usage: {start|stop}" >&2
		exit 1
		;;
esac

exit 0
