#!/bin/bash
#
# Temporary script to start tgt and istgt
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
MEM_SIZE=1048576
export LD_LIBRARY_PATH=${PWD}/usr:${PWD}/istgt/usr:${PWD}/ibmvstgt/usr:${LD_LIBRARY_PATH}

if [ -f ${PWD}/istgt/kernel/istgt_tcp.ko ] ; then
	TARGET=istgt
fi

start_server()
{
	insmod ${PWD}/kernel/scsi_tgt_core.ko

	if [ "$TARGET" = "istgt" ] ; then
		modprobe -q crc32c
		insmod ${PWD}/istgt/kernel/scsi_transport_iscsi.ko
		insmod ${PWD}/istgt/kernel/libiscsi.ko
		insmod ${PWD}/istgt/kernel/istgt_tcp.ko
		${PWD}/istgt/usr/istgtd
	else
		insmod ${PWD}/ibmvstgt/kernel/libsrp.ko
		insmod ${PWD}/ibmvstgt/kernel/ibmvstgt.ko
	fi

	${PWD}/usr/tgtd -d0

	sleep 1
}
	
stop_server()
{
	if [ "$TARGET" = "istgt" ] ; then
		${PWD}/usr/tgtadm --driver istgt --op delete
		killall -9 istgtd
	else
		${PWD}/usr/tgtadm --driver ibmvstgt --op delete
	fi

	killall -9 tgtd

	sleep 1

	if [ "$TARGET" = "istgt" ] ; then
		rmmod istgt_tcp
		rmmod libiscsi
		rmmod scsi_transport_iscsi
	else
		rmmod libsrp
		rmmod ibmvstgt
	fi

	rmmod scsi_tgt_core
}

case "$1" in
	start)
		start_server
		;;
	stop)
		stop_server
		;;
	*)
		echo "Usage: {start|stop}" >&2
		exit 1
		;;
esac

exit 0
