#!/bin/bash
#
# Temporary script to start istgt
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin

${PWD}/usr/tgtadm --driver istgt --op new --tid 1 --params iqn.2001-04.com.example:storage.disk2.amiens.sys1.xyz
${PWD}/usr/tgtadm --driver istgt --op new --tid 1 --lun 0 --params Path=/dev/hdc1
