.\"     Title: tgtimg
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 04/04/2010
.\"    Manual: 
.\"    Source: 
.\"
.TH "TGTIMG" "8" "04/04/2010" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
tgtimg - Linux SCSI Target Framework Image File Utility
.SH "SYNOPSIS"
.HP 7
\fBtgtimg\fR [\-o\ \-\-op\ <operation>] [\-Y\ \-\-device\-type\ <device\-type>] [\-b\ \-\-barcode\ <barcode>] [\-s\ \-\-size\ <size>] [\-t\ \-\-type\ <media\-type>] [\-f\ \-\-file\ <path>]
.HP 14
\fBtgtimg \-\-help\fR
.SH "DESCRIPTION"
.PP
Tgtimg is a utility to create and manage the image files used by the TGTD device emulation\.
.PP
This command is used to initialize device image files with the additional metadata, such as barcode, list of blocks, total size, etc that the TGTD emulation needs\.
.SH "OPTIONS"
.PP
\fB\-h, \-\-help\fR
.RS 4
Show a help screen and exit\.
.RE
.PP
\fB\-o, \-\-op {new|show}\fR
.RS 4
Operation\. Is either new to create a new image file or show to show the content of an existing image file\.
.RE
.PP
\fB\-Y, \-\-device\-type <type>\fR
.RS 4
This specifies the type of image file\.
.RE
.sp
.RS 4
.nf
Supported device types are :
    cd   : to create media for a dvd device
    disk : to create media for a disk device
    tape : to create media for a tape device
      
.fi
.RE
.PP
\fB\-t, \-\-type <media\-type>\fR
.RS 4
When creating a new image, this specifies the type of media to emulate\. The available mediatypes depend on the type of the device\.
.RE
.sp
.RS 4
.nf
Supported media types for cd devices are :
    dvd+r : create a blank writeable DVD+R disk

Supported media types for disk devices are :
    disk  : create an empty disk

Supported media types for tape devices are :
    data  : create a normal data tape
    clean : create a cleaning tape
    worm  : create a worm
      
.fi
.RE
.PP
\fB\-b, \-\-barcode <barcode>\fR
.RS 4
When creating a new image, this argument specifies the barcode to use with this image file\. Backup application software often uses barcodes to identify specific tapes\. When emulating a VTL, make sure that all tape images use unique barcodes\.
.RE
.PP
\fB\-s, \-\-size <size>\fR
.RS 4
When creating a new image, this specifies the size in megabytes for the virtual tape image\.
.RE
.PP
\fB\-f, \-\-file <path>\fR
.RS 4
The filename of the image file\.
.RE
.SH "EXAMPLES"
.PP
To create a new 100MByte disk
.sp
.RS 4
.nf
      tgtimg \-\-op new \-\-device\-type disk \-\-type disk \-\-size 100 \-\-file /data/hd001\.raw
    
.fi
.RE
.PP
To create a new tape image
.sp
.RS 4
.nf
      tgtimg \-\-op new \-\-device\-type tape \-\-barcode 12345 \-\-size 100 \-\-type data \-\-file /data/tape001\.img
    
.fi
.RE
.PP
To view the content of an existing image
.sp
.RS 4
.nf
      tgtimg \-\-op show \-\-device\-type tape \-\-file /data/tape001\.img
    
.fi
.RE
.PP
To create a new blank DVD+R image
.sp
.RS 4
.nf
      tgtimg \-\-op new \-\-device\-type cd \-\-type dvd+r \-\-file /data/dvd001\.iso
    
.fi
.RE
.SH "SEE ALSO"
.PP
tgtd(8), tgtadm(8), tgt\-admin(8), tgt\-setup\-lun(8)\.
\fI\%http://stgt.sourceforge.net/\fR
.SH "REPORTING BUGS"
.PP
Report bugs to <stgt@vger\.kernel\.org>
