#!/bin/bash

# Parent directory for data files..
HOME=/d/01

P=`ps -ef|grep -v grep|grep tgtd|wc -l`
if [ "X"$P == "X0" ]; then
	tgtd -d 1
	sleep 1
fi

if [ ! -d $HOME ]; then
	mkdir -p $HOME
fi

if [ ! -f $HOME/hd_block ]; then
	dd if=/dev/zero of=$HOME/hd_block bs=1M count=8
fi
if [ ! -f $HOME/cd_block0 ]; then
	dd if=/dev/zero of=$HOME/cd_block0 bs=1M count=8
fi
if [ ! -f $HOME/cd_block1 ]; then
	dd if=/dev/zero of=$HOME/cd_block1 bs=1M count=8
fi
if [ ! -f $HOME/cd_block2 ]; then
	dd if=/dev/zero of=$HOME/cd_block2 bs=1M count=8
fi

set -x

###############################################################################
# Set up SBC HDD device
###############################################################################
TID=1

# Create Target ID 1..
tgtadm --lld iscsi --mode target --op new --tid $TID \
		-T iqn.2007-03:marks-vtl_sbc:`hostname`
sleep 1

# Create first LUN - Disk
LUN=1
tgtadm --lld iscsi --mode logicalunit --op new --tid $TID --lun $LUN -b $HOME/hd_block --device-type=disk

tgtadm --lld iscsi --mode logicalunit --op update --tid $TID --lun $LUN \
	--params scsi_sn=FRED00,scsi_id=Fred

tgtadm --lld iscsi --mode logicalunit --op update --tid $TID --lun $LUN \
	--params vendor_id=QUANTUM,product_id=HD100,product_rev=0010,removable=1,sense_format=0

# Create 2nd LUN - CD/ROM
LUN=2
tgtadm --lld iscsi --mode logicalunit --op new --tid $TID --lun $LUN -b $HOME/cd_block0 --device-type=cd
tgtadm --lld iscsi --mode logicalunit --op update --tid $TID --lun $LUN \
	--params vendor_id=VirtualCD,product_id=CD101,product_rev=0010,scsi_sn=XYZZY11,removable=1

# Create 3rd LUN - CD/ROM
LUN=3
tgtadm --lld iscsi --mode logicalunit --op new --tid $TID --lun $LUN -b $HOME/cd_block1 --device-type=cd
tgtadm --lld iscsi --mode logicalunit --op update --tid $TID --lun $LUN \
	--params vendor_id=VirtualCD,product_id=CD101,product_rev=0010,scsi_sn=XYZZY12,removable=1

# Create 4th LUN - CD/ROM
LUN=4
tgtadm --lld iscsi --mode logicalunit --op new --tid $TID --lun $LUN -b $HOME/cd_block1 --device-type=cd
tgtadm --lld iscsi --mode logicalunit --op update --tid $TID --lun $LUN \
	--params vendor_id=VirtualCD,product_id=CD101,product_rev=0010,scsi_sn=XYZZY13,removable=1

# Allow ALL initiators to connect to this target
tgtadm --lld iscsi --mode target --op bind --tid $TID -I ALL


# Show all our good work.
tgtadm --lld iscsi --mode target --op show


